import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, parse as parsePath, resolve } from 'node:path';
import { compileMessage } from '~/features/messages/compile.js';
import type { Bucket, Config } from '~/shapes.js';
import { expandBucketOutputPath } from './path.js';
import { assembleCatalogueRecord, resolveFallbackChain } from './record.js';

/**
 * The generated module a locale is actually imported as.
 *
 * The catalogue file on disk is what a translator edits; this is what a bundler
 * sees. It is a real file, so an ordinary module graph, an ordinary watch and
 * an ordinary hot update all apply to it, and no bundler needs teaching how to
 * read a catalogue format.
 */

/**
 * The declaration beside the generated module.
 *
 * Every call site is written by the transform, never by hand, so there is
 * nothing per-id worth typing. It is the same two lines for every locale and
 * never changes, which is why it is committed while the module it types is
 * not: `tsc` passes on a fresh clone without anything having been generated.
 */
const DECLARATION_CONTENT = `
import type { Message } from 'saykit';

declare const messages: Record<string, Message>;
export default messages;
`.trimStart();

/** Where a locale's generated module goes: beside its catalogue, as `.js`. */
export function modulePathFor(bucket: Bucket, locale: string) {
  const { dir, name } = parsePath(expandBucketOutputPath(bucket, locale));
  return resolve(dir, `${name}.js`);
}

/**
 * Build the source of a locale's generated module from its assembled record.
 *
 * The module is data and nothing else: no imports, no functions, no locale
 * bound into it. A view compiles what it reads from here, so the same messages
 * can be handed across a server/client boundary as the JSON they already are.
 *
 * @param record The locale's messages, keyed by id, as ICU
 */
export function generateCatalogueModule(record: Record<string, string>) {
  const entries = Object.entries(record).map(([id, icu]) => {
    // ponytail: the one call site that decides how a message is compiled. A
    // `compiler` slot on the bucket config replaces this line when a second
    // message format turns up
    const message = compileMessage(icu);

    // The message it came from, so the file can be read and reviewed
    const comment = icu
      .split('\n')
      .map((line) => `  // ${line}`)
      .join('\n');
    return `${comment}\n  ${JSON.stringify(id)}: ${JSON.stringify(message)},`;
  });

  return (
    '// Generated by saykit. Do not edit.\n' + `export default {\n${entries.join('\n\n')}\n};\n`
  );
}

/**
 * Compile one locale's catalogue, and its fallbacks, into a module on disk.
 *
 * The fallback chain is merged here, so an untranslated key resolves to a
 * fallback string while the app still imports a single module per locale.
 */
export async function emitCatalogueModule(config: Config, bucket: Bucket, locale: string) {
  const sources = resolveFallbackChain(config, locale).map((l) =>
    expandBucketOutputPath(bucket, l),
  );
  const contents = await Promise.all(
    sources.map((source) => readFile(source, 'utf8').catch(() => '')),
  );

  const record = assembleCatalogueRecord(bucket, contents);
  const path = modulePathFor(bucket, locale);

  await mkdir(dirname(path), { recursive: true });
  await Promise.all([
    writeFile(path, generateCatalogueModule(record)),
    writeFile(path.replace(/\.js$/, '.d.ts'), DECLARATION_CONTENT),
  ]);

  return { path, count: Object.keys(record).length };
}
