[package]
name = "sayable_swc_plugin"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true          # link-time optimisation
opt-level = "z"     # optimise for size (or "s")
codegen-units = 1   # allow max cross-crate optimisations
panic = "abort"     # remove unwinding machinery
strip = "debuginfo"

[dependencies]
sayable_factory = { path = "../factory" }
swc_core = { version = "44.0.2", features = ["ecma_plugin_transform"] }
